spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: customer
    password: customer123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080