spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: customer
    password: customer123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:customer}
    password: ${RABBITMQ_PASS:customer123}

server:
  port: 8080

messaging:
  enabled: false
  customer:
    topic: customer.events.v1
  rabbit:
    enabled: false
    exchange: customer.events
    routing:
      created: customer.created
      updated: customer.updated
      deleted: customer.deleted
